 ----------------
#### **Author Name :** Muhammad Muneer Hussain
#### **Linkedin :** [Click Here](https://www.linkedin.com/in/muneer-hussain-ai/)
#### **Github :** [Click Here](https://github.com/Muhammad-Muneer-Hussain)
#### **Gmail :** muhammadmuneerhussain85@gmail.com

-----------------------------

## Fancy indexing

In [6]:
import numpy as np

In [2]:
arr2d = np.arange(36).reshape(4,9)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [3]:
arr2d[:,[5,8,0,3]]

array([[ 5,  8,  0,  3],
       [14, 17,  9, 12],
       [23, 26, 18, 21],
       [32, 35, 27, 30]])

In [4]:
arr2d[[0,2],[2,7]]

array([ 2, 25])

In [7]:
arr2d[:,::3]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [8]:
arr2d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [9]:
arr3d = np.arange(64).reshape(4,4,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [10]:
arr3d[1][2][2]

np.int64(26)

In [14]:
arr3d[3][1][3]

np.int64(55)

In [16]:
arr3d[3][1:3][1:3]

array([[56, 57, 58, 59]])

In [17]:
arr3d[3:4,1:3,1:3]

array([[[53, 54],
        [57, 58]]])

In [19]:
arr3d[:,2:3,1:3]

array([[[ 9, 10]],

       [[25, 26]],

       [[41, 42]],

       [[57, 58]]])

In [24]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((4,5),dtype='float')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((4,5),dtype='float')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.ones((5,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [32]:
np.ones((3,5,2),dtype='int')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
arr2d1 = np.arange(12).reshape(3,4)
arr2d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
arr2d2 = np.random.randn(3,4)

In [43]:
arr2d1 + arr2d2

array([[-1.99228693e-01, -4.64238522e-04,  2.13128745e-01,
         3.36589826e+00],
       [ 3.68494859e+00,  5.35375213e+00,  6.09304803e+00,
         8.51233081e+00],
       [ 9.45249363e+00,  1.04713990e+01,  1.03097560e+01,
         1.00358378e+01]])

In [44]:
arr2d3 = np.random.randn(4,4)
arr2d3

array([[ 0.50206484,  0.23308018, -0.55958774,  2.09857425],
       [-2.64464591,  0.65024119,  0.1625339 ,  0.663267  ],
       [ 0.27223154,  0.11969517, -0.65283707, -0.13152532],
       [ 0.44121251, -1.41191326, -0.63824994, -0.11733847]])

In [47]:
arr2d3 + arr2d2 #shape is not same

ValueError: operands could not be broadcast together with shapes (4,4) (3,4) 

In [48]:
arr2d4 = np.ones((3,3))*2
arr2d4

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [50]:
arr2d5 = np.ones((3,3))*3
arr2d5

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [51]:
# mirror multiplicztion
arr2d5 * arr2d4

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [54]:
a = np.arange(6).reshape(3,2)
b = np.arange(6).reshape(2,3)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [55]:
a*b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [56]:
b*a

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [57]:
# Matrix Multiplication
# Column of first == Rows of second (Checking operation)
# Row of first * Column of second (Multiply operation)
a@b

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [59]:
b@a

array([[10, 13],
       [28, 40]])

In [62]:
c = np.arange(15).reshape(5,3)
d = np.arange(10).reshape(2,5)
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [61]:
c@d

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [63]:
d@c

array([[ 90, 100, 110],
       [240, 275, 310]])

In [64]:
d.dot(c)

array([[ 90, 100, 110],
       [240, 275, 310]])

In [65]:
np.full((4,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [66]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [68]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [69]:
np.ones_like(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [70]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [71]:
arr2d > 5

array([[False, False, False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [72]:
(arr2d > 5).sum()

np.int64(30)

In [73]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [74]:
arr2d[arr2d>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [75]:
arr2d[(arr2d >10)  &  (arr2d<30)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [76]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [77]:
new3darray = arr3d.ravel()
new3darray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [78]:
arr3d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [79]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [80]:
arr3d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [81]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [82]:
arr3d.reshape(64)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])