----------------
#### **Author Name :** Muhammad Muneer Hussain
#### **Linkedin :** [Click Here](https://www.linkedin.com/in/muneer-hussain-ai/)
#### **Github :** [Click Here](https://github.com/Muhammad-Muneer-Hussain)
#### **Gmail :** muhammadmuneerhussain85@gmail.com

-----------------------------

# ***<U>NumPy & pandas funcitons</U>***

This notebook introduces the basics of **NumPy** and **pandas**. We'll cover basic operations.

## NumPy Basics

NumPy provides support for large multi-dimensional arrays and matrices, along with mathematical functions to operate on them.

In [1]:
import numpy as np

### Creating Arrays
Use `np.array()` to create arrays.

In [41]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr1, arr2

(array([1, 2, 3, 4]),
 array([[1, 2, 3],
        [4, 5, 6]]))

### Array Operations
You can perform element-wise operations like addition, multiplication, and division.

In [3]:
arr = np.array([10, 20, 30, 40])
arr + 5, arr * 2, arr / 10



(array([15, 25, 35, 45]), array([20, 40, 60, 80]), array([1., 2., 3., 4.]))

### Useful Functions
NumPy provides several useful functions for creating arrays quickly.

#### `np.zeros`
Creates an array filled with zeros.

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### `np.ones`
Creates an array filled with ones.

In [5]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### `np.eye(n)`

Identity matrix (diagonal 1s, rest 0s)

In [6]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### `np.arange`
Creates an array with regularly spaced values within a given range.

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

#### `np.linspace`
Creates an array with evenly spaced values between a start and end value.

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### `np.random.rand`

* Generates random numbers uniformly distributed between 0 and 1.

* All values are between [0, 1) (never equal to 1).

* Useful for normalized random values.

In [9]:
arr = np.random.rand(3)
print(arr)

[0.692767   0.55781049 0.56384063]


#### `np.random.randn`

* Generates random numbers from a standard normal distribution:

    * Mean = 0

    * Standard deviation = 1

* Values can be negative or positive.

In [10]:
arr = np.random.randn(3)
print(arr)

[ 1.97406856 -0.86962686  0.81018558]


#### `np.random.randint(low, high=None, size=None)`

* Generates random integers.

* If high is given → numbers are between [low, high).

* If only low is given → numbers are between [0, low).

In [11]:
arr = np.random.randint(1, 10, 5)
print(arr)

[6 9 5 5 5]


#### `np.transpose`

* np.transpose rearranges the axes of an array.

* For a 2D array (matrix), it flips rows ↔ columns.

* For higher dimensions, you can specify the order of axes.

In [12]:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original:\n", arr)
print("Transposed:\n", np.transpose(arr))

Original:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


### Statistics
Functions like `mean`, `sum`, `std`, `median`, `max` and `min` allow quick statistical calculations.

In [13]:
arr = np.array([1,2,3,4,5])
arr.mean(), arr.sum(), arr.std(), np.median(arr), np.max(arr), np.min(arr)

(np.float64(3.0),
 np.int64(15),
 np.float64(1.4142135623730951),
 np.float64(3.0),
 np.int64(5),
 np.int64(1))

### Shape and Reshape

#### `np.reshape(arr, new_shape)`

Reshape array

In [14]:
arr = np.array([[1,2],[3,4]])
print(arr.reshape(4,))

[1 2 3 4]


#### `np.concatenate([a, b])`

Join arrays

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate([arr1, arr2]))

[1 2 3 4 5 6]


#### `np.flatten() or arr.ravel()`

Flatten into 1D

In [16]:
arr1 = np.array([[1, 2], [4, 5]])
print(arr1.ravel()) # returns a view not a copy
arr2 = np.array([[1, 2], [4, 5]])
print(arr2.flatten()) # returns a copy


[1 2 4 5]
[1 2 4 5]


### Indexing & Conditions

#### `np.where(condition, x, y)`

Choose values based on condition

In [17]:
arr = np.array([10, 20, 30, 40])
print(np.where(arr > 25, "big", "small"))

['small' 'small' 'big' 'big']


#### `np.unique(arr)`

Get unique elements

In [18]:
arr1 = np.array([1, 2, 3, 4, 3, 2, 1])
print(np.unique(arr1))

[1 2 3 4]


#### `np.sort(arr)`

Sort array

In [19]:
arr1 = np.array([1, 2, 4, 8, 3, 6, 9, 5, 7])
print(np.sort(arr1))

[1 2 3 4 5 6 7 8 9]


## Pandas Basics

Pandas is built on top of NumPy and provides two main data structures:
- **Series**: One-dimensional labeled array
- **DataFrame**: Two-dimensional labeled data structure (like an Excel sheet)

In [20]:
import pandas as pd

### Creating a Series
A `Series` is like a column in a spreadsheet.

In [21]:
s = pd.Series([10, 20, 30, 40], index=['a','b','c','d'])
s, s['b']

(a    10
 b    20
 c    30
 d    40
 dtype: int64,
 np.int64(20))

### Creating a DataFrame
A `DataFrame` is like a complete spreadsheet with rows and columns.

In [42]:
data = {
    'Name': ['Muhammad', 'Muneer', 'Hussain'],
    'Age': [25, 30, 35],
    'City': ['Lahore', 'Islamabad', 'Karachi']
}
df = pd.DataFrame(data)
df

Name  Age       City
0  Muhammad   25     Lahore
1    Muneer   30  Islamabad
2   Hussain   35    Karachi

### DataFrame Operations

#### `head()`
Shows the first 5 rows by default. You can also specify `n` to change the number of rows.

In [43]:
df.head()

Name  Age       City
0  Muhammad   25     Lahore
1    Muneer   30  Islamabad
2   Hussain   35    Karachi

In [44]:
df.head(2)

Name  Age       City
0  Muhammad   25     Lahore
1    Muneer   30  Islamabad

#### `describe()`
Provides summary statistics for numerical columns.

In [46]:
df.describe() #statistical Summary

Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

#### Column Selection
Select a single column or multiple columns.

In [47]:
df['Name']

0    Muhammad
1      Muneer
2     Hussain
Name: Name, dtype: object

In [48]:
df[['Name','Age']]

Name  Age
0  Muhammad   25
1    Muneer   30
2   Hussain   35

#### `iloc`
Select rows and columns by **integer position**.

In [54]:
df.iloc[0]  #

Name    Muhammad
Age           25
City      Lahore
Name: 0, dtype: object

In [55]:
df.iloc[:, 0]  # first column

0    Muhammad
1      Muneer
2     Hussain
Name: Name, dtype: object

In [56]:
df.iloc[0:2, 0:2]  # first 2 rows and 2 columns

Name  Age
0  Muhammad   25
1    Muneer   30

#### `loc`
Select rows and columns by **labels**.

In [57]:
df.loc[1]  # row with index 1

Name       Muneer
Age            30
City    Islamabad
Name: 1, dtype: object

In [58]:
df.loc[:, 'Name']  # 'Name' column

0    Muhammad
1      Muneer
2     Hussain
Name: Name, dtype: object

In [59]:
df.loc[0:1, ['Name','Age']]  # rows 0 and 1, columns Name and Age

Name  Age
0  Muhammad   25
1    Muneer   30

### Adding and Modifying Columns

In [60]:
df['Country'] = ['USA','France','UK']
df['Age'] = df['Age'] + 1
df

Name  Age       City Country
0  Muhammad   26     Lahore     USA
1    Muneer   31  Islamabad  France
2   Hussain   36    Karachi      UK

### Filtering Data
Filter rows based on conditions.

In [61]:
df[df['Age'] > 30]


Name  Age       City Country
1   Muneer   31  Islamabad  France
2  Hussain   36    Karachi      UK

#### `where`

In [62]:
result = df.where(df['Age'] > 30, other='Below 30')
print(result)

       Name       Age       City   Country
0  Below 30  Below 30   Below 30  Below 30
1    Muneer        31  Islamabad    France
2   Hussain        36    Karachi        UK


### Grouping and Aggregation
Group rows and apply aggregation functions.

In [63]:
df.groupby('Country')['Age'].mean()

Country
France    31.0
UK        36.0
USA       26.0
Name: Age, dtype: float64

### Renaming Columns

In [68]:
# Create a sample DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})
print("Original DataFrame:\n", df)



Original DataFrame:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


#### `rename`

In [71]:
# Rename specific columns using a dictionary
df_rename = df.rename(columns={'A': 'X', 'B': 'Y'})
print("\nRenamed using .rename():\n", df_rename)




Renamed using .rename():
    X  Y  C
0  1  4  7
1  2  5  8
2  3  6  9


#### `.columns`

In [66]:
# Rename all columns by assigning a new list
df.columns = ['E', 'F', 'G']
print("\nRenamed using .columns assignment:\n", df)


Renamed using .columns assignment:
    E  F  G
0  1  4  7
1  2  5  8
2  3  6  9
